name = "blob-storage-back"
main = "src/index.ts"
compatibility_date = "2024-04-19"
node_compat = true
[vars]
CF_REGION = "auto"
CF_ENDPOINT = "https://a7f4ae46a74288d55c7347b7e37bb563.r2.cloudflarestorage.com"
CF_ACCESS_KEY_ID = "b580dbfb100c3f8bdc8e3aba509db176"
CF_SECRET_ACCESS_KEY = "ea683393998308ecd3a425ceb8f780d0ae69a5d10ecc244018accbf7c71537fa"
CF_BUCKET = "blob-storage"
CF_BUCKET_FILE_URL = "https://pub-b188ccc05781439580b74ded05f108ef.r2.dev"